:sectnums!:
:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:
:imagesdir: ./images

== PodSecurityPolicy Demonstration

***Scenario-1***

Create a `podsecuritypolicy` to restrict  the containers with `root` privilege from running in the cluster.

=== Create namespace and serviceaccount for the demo

. Setup a namespace for the demo pods
+
[%nowrap]
----
kubectl create namespace meetup-demo
----
+

. Create a serviceaccount in the namespace

+
[%nowrap]
----
kubectl create serviceaccount -n meetup-demo meetup-user
----
+

. Assign `edit` role to the newly created service account
+
[%nowrap]
----
kubectl create rolebinding -n meetup-demo meetup-user --clusterrole=edit --serviceaccount=meetup-demo:meetup-user
----
+

[NOTE]
The ` edit` ClusterRole,  allows the user to modify resources in a namespace include that of reading and modifying Secrets. It doesn’t, however, allow viewing or modifying Roles or RoleBindings—again, this is to prevent privilege escalation.


. To save some typing and visual clarity `(we are mere mortals!!!)`create  aliase for the admin and the demo-user respectively.

+
[%nowrap]
----
alias kubectl-admin='kubectl -n meetup-demo'
----
+

+
[%nowrap]
----
alias kubectl-user='kubectl --as=system:serviceaccount:meetup-demo:meetup-user -n meetup-demo'
----
+


=== Enforce PodSecurityPolicy

. Prepare manifest for a `podsecuritypolicy` which preventing the pods from running with root privilege
+
[%nowrap]
----
cat <<EOF >>restricted-policy.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
EOF
----
+

. Create the podsecuritypolicy using the manifest

+
[%nowrap]
----
kubectl-admin create -f restricted-policy.yaml
----
+

. List and verify the podsecuritypolicy
+
[%nowrap]
----
kubectl-admin get psp
----
+

+
[%nowrap]
.Sample Output
----
[root@k8s-master ~]# kubectl-admin get psp
NAME         PRIV    CAPS   SELINUX    RUNASUSER          FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
restricted   false          RunAsAny   MustRunAsNonRoot   RunAsAny   RunAsAny   false            configMap,downwardAPI,emptyDir,persistentVolumeClaim,projected,secret
----
+

. Create  manifest for pod with a container image require root privilege (eg:docker.io/wordpress)
+
[%nowrap]
----
cat <<EOF >> wp-root-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: wprootpod
spec:
  containers:
    - name:  wordpress
      image: docker.io/wordpress
EOF

----
+

. Create manifest for a  pod with a container image needs only non-root privilege (eg:openshift/hello-openshift:v3.9)
+
[nowrap]
----
cat <<EOF >> non-root-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
spec:
  containers:
    - name:  hello-opemshift
      image: openshift/hello-openshift:v3.9
EOF
----
+
. Create pod with the non-root container
+
[%nowrap]
----
kubectl-user create -f non-root-pod.yaml
----
+

You may expect an error message  message
+
[%nowrap]
.Sample Output
----
Error from server (Forbidden): error when creating "wp-roor-pod.yaml": pods "wprootpod" is forbidden: unable to validate against any pod security policy: []
----
+


=== Create roles and rolebindings to use the PodSecurityPolicy

. Check the privilege of the user to use the PodSecurityPolicy resource
+
[%nowrap]
----
kubectl-user auth can-i use psp/restricted
----
+

+
[%nowrap]
.Sample Output
----
kubectl-user auth can-i use podsecuritypolicy/restricted
no
----
+

. Create a `role` with `rule` to `use` the podsecuritypolicy resource `restricted`
[IMPORTANT]
Admin privilege is required to create rules and assign it to users

+
[%nowrap]
----
kubectl-admin  create role psp:unprivileged --verb=use --resource=podsecuritypolicy --resource-name=restricted 
----
+

. Bind the role to the user

+
[%nowrap]
----
kubectl-admin create rolebinding meetup-user:psp:unprivileged --role=psp:unprivileged --serviceaccount=meetup-demo:meetup-user
----
+

. As the user verify the access of podsecuritypolicy resource

+
[%nowrap]
----
kubectl-user auth can-i use psp/restricted
----
+

+
[%nowrap]
.Sample Output
----
kubectl-user auth can-i use podsecuritypolicy/restricted
yes
----
+


=== Test the PodSecurityPolicy

. Create the pod with non-root privilege
+
[%nowrap]
----
kubectl-user create -f non-root-pod.yaml
----
+

. List  and verify the pod status
+
[%nowrap]
----
kubectl-user get po 
----
+

+
[%nowrap]
.Sample Output
----
NAME              READY   STATUS    RESTARTS   AGE
hello-openshift   1/1     Running   0          13s
----
+
. Create the pod require root privilege
+
[%nowrap]
----
kubectl-user create -f wp-root-pod.yaml
----
+

. Watch the status of the pod 
+
[%nowrap]
----
kubectl-user get po -w 
----
+

+
[%nowrap]
.Sample Output
----
[root@k8s-master ~]# kubectl-user get po -n meetup-demo
NAME              READY   STATUS                       RESTARTS   AGE
hello-openshift   1/1     Running                      0          92m
wprootpod         0/1     CreateContainerConfigError   0          89m
----
+

. List the events to find the cause of the error.
+
[%nowrap]
----
kubectl-user get events
----
+

+
[%nowrap]
.Sample Output
----
[root@k8s-master ~]# kubectl-user get events
LAST SEEN   TYPE      REASON      KIND   MESSAGE
3m40s       Normal    Scheduled   Pod    Successfully assigned meetup-demo/hello-openshift to k8s-node1
3m39s       Normal    Pulling     Pod    pulling image "openshift/hello-openshift:v3.9"
3m31s       Normal    Pulled      Pod    Successfully pulled image "openshift/hello-openshift:v3.9"
3m31s       Normal    Created     Pod    Created container
3m30s       Normal    Started     Pod    Started container
75s         Normal    Scheduled   Pod    Successfully assigned meetup-demo/wprootpod to k8s-node1
16s         Normal    Pulling     Pod    pulling image "docker.io/wordpress"
11s         Normal    Pulled      Pod    Successfully pulled image "docker.io/wordpress"
11s         Warning   Failed      Pod    Error: container has runAsNonRoot and image will run as root
----
+


***Scenario:2***

===  Allocate privilege policy to the user

Create a `podsecuritypolicy` to allow  the root privileged containers to  running in the cluster.Bind the policy access to the restricted user.

. Go ahead and create a  `podsecuritypolicy` manifest  allows  the `root privilege` pods
+
[%nowrap]
----
cat <<EOF >>privileged-policy.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
EOF
----
+

. Create the privileges podsecuritypolicy

+
[%nowrap]
----
kubectl-admin create -f privileged-policy.yaml
----
+

. Create a `role` with rules to acces the podsecuritypolicy `privileged`
+
[%nowrap]
----
kubectl-admin  create role psp:privileged --verb=use --resource=podsecuritypolicy --resource-name=privileged
----
+

. Bind the role to the serviceaccount
+
[%nowrap]
----
kubectl-admin create rolebinding meetup-user:psp:privileged --role=psp:privileged --serviceaccount=meetup-demo:meetup-user
----
+

. Create the pod which requires root privilege and verify the status
+
[%nowrap]
----
kubectl-user create -f wp-root-pod.yaml
----
+

[TIP]

You may delete the pod in error state prior to creating the new pod with same name

+
[%nowrap]
----
kubectl-user get po -w
----
+

